@baseUrl = http://localhost:8080/api/v1
@token = your_jwt_token_here

### Add a new todo
POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Read Today",
  "description": "todo blah blah blah"
}

### Get all todos
GET {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a todo by id
GET {{baseUrl}}/todos/6
Authorization: Bearer {{token}}

### Update a todo (no trailing comma)
PATCH {{baseUrl}}/todos/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Do Assignment",
  "description": "todo all"
}

### Delete a todo
DELETE {{baseUrl}}/todos/6
Authorization: Bearer {{token}}