### Add a new todo
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Read Today",
  "description": "todo blah blah blah"
}

### Get all todos
GET http://localhost:8080/todos

### Get a todo
GET http://localhost:8080/todos/2

### Update a todo
PATCH  http://localhost:8080/todos/2
Content-Type: application/json

{
  "title": "Do Assignment",
  "description": "todo all",
}

### Delete a todo
DELETE http://localhost:8080/todos/3

### Get a user
GET http://localhost:8080/auth/taofeekabdulazeez2020@gmail.com

### Sign In
POST  http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "email": "taofeekabdulazeez2020@gmail.com",
  "password": "Taofeek@11"
}