### Add a new todo
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Do second Assignment",
  "assignee": "Emmaneul Balogun",
  "status": "completed",
  "description": "todo blah blah blah",
  "dueDate": "2025-03-09"
}

### Get all todos
GET http://localhost:8080/todos

### Get a todo
GET http://localhost:8080/todos/2

### Update a todo
PATCH  http://localhost:8080/todos/3
Content-Type: application/json

{
  "title": "Do Assignment",
  "priority": "high",
  "assignee": "Balogun Elias",
  "description": "todo all",
}

### Delete a todo
DELETE http://localhost:8080/todos/2